### ISSUE TITLE
LEGIT SUGGESTION: UPDATE NOW 

### ISSUE THREAD

**Issue by joalricha869** [IdkDwij/Termithon#11]
Hey dwij, please mantain this app alive

**Comment by joalricha869** [comment]
i think dwij died

**Comment by joalricha869** [comment]
yea i think dwij died

**Comment by joalricha869** [comment]
bro replaced cmd with args[0] imagine a revolution indeed 

make new features man

**Comment by IdkDwij** [comment]
Im working on something

**Comment by IdkDwij** [comment]
nah, im moving soon to NJ

**Comment by joalricha869** [comment]
rip 💀

**Comment by IdkDwij** [comment]
?
