### ISSUE TITLE
Unrelated

### ISSUE THREAD

**Issue by theclosedbitter** [IdkDwij/Termithon#14]
I know this unrelated but what happened to https://dwij.nxweb.xyz/? Did Andrew kick you off his server?

**Comment by IdkDwij** [comment]
no, idk it just goes down i dont feel like trying to keep running it, also hi diego

**Comment by theclosedbitter** [comment]
hi dwij

**Comment by joalricha869** [comment]
diego is still alive

**Comment by theclosedbitter** [comment]
Jose is still alive?

**Comment by joalricha869** [comment]
yup im alive
