### ISSUE TITLE
wheres ur update dwijjjjj

### ISSUE THREAD

**Issue by joalricha869** [IdkDwij/Termithon#16]
i forgor 💀💀💀💀

**Comment by IdkDwij** [comment]
I will kill you even if I moved about 20 hours worth of driving away 💀

**Comment by IdkDwij** [comment]
You have made 16 issues already

**Comment by theclosedbitter** [comment]
> I will kill you even if I moved about 20 hours worth of driving away skull

What? You moved back to India?

**Comment by joalricha869** [comment]
no hes in ohio

**Comment by IdkDwij** [comment]
> > I will kill you even if I moved about 20 hours worth of driving away skull
> 
> What? You moved back to India?

Thats 27 hours of flight, im in new jersey use your brain diego

**Comment by joalricha869** [comment]
frfr
