### ISSUE TITLE
Dumb question, but _why?_

### ISSUE THREAD

**Issue by therealandreww** [IdkDwij/Termithon#21]
Making a terminal in Python, is a bit _inefficient_. I don't get the point of doing this anyway, no offense tho. Python is a really slow language and isn't really easy to debug. I would make a terminal if I used C/C++ as the main language.

**Comment by IdkDwij** [comment]
I was trolling :\

**Comment by therealandreww** [comment]
May I convert this into a cross-platform Rust-based terminal as a slight "improvement"? I'll let you know about the progress. (it's gonna take long since developing a windows app from macos is complicated but i'll try it with wine)

**Comment by IdkDwij** [comment]
@therealandreww sure
